spring.application.name=db
#conexao com MySql

spring.datasource.url=\jdbc:mysql://localhost:3306/produtosdb
spring.datasource.username = root
spring.datasource.password = MdpA200101$$

#JPA/ HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
